In [2]:
from data_loader.BatchEnv import BatchGlobalFeatureEnv
import numpy as np
import os

In [3]:
replays_path = 'train_val_test/Terran_vs_Terran'
dataset_path = 'train.json'
path = os.path.join(replays_path, dataset_path)

race = 'Terran'
enemy_race = 'Terran'

n_steps = 1500
n_replays = 100
epochs = 1
replays = []

In [19]:
env = BatchGlobalFeatureEnv()
env.init(path, './', race, enemy_race, n_steps=n_steps, 
         seed=None, n_replays=n_replays, epochs=epochs)



Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

In [20]:
replays = env.step()




  Replays:   0%|          | 0/6854 [00:00<?, ?it/s]


  Replays:   0%|          | 1/6854 [00:00<33:35,  3.40it/s]


  Replays:   1%|▏         | 88/6854 [00:00<23:15,  4.85it/s]

In [21]:
np.shape(replays)

(2,)

In [56]:
len(replays[0])

2

In [57]:
np.shape(replays[0][0]) # data for each episode

(1500, 100, 738)

In [58]:
np.shape(replays[0][1]) # appears to be reward vector (0/1)

(1500, 100, 1)

In [44]:
replays[0][1][0][:5] # look at first five rewards

array([[1.],
       [0.],
       [0.],
       [1.],
       [0.]])

In [65]:
replays[0][1][45][1]

array([0.])

In [79]:
replays[0][0][450][0] # features for first timestep in first replay

array([0.09613468, 0.01247051, 0.01707504, 0.705     , 0.63      ,
       0.345     , 0.285     , 0.00819672, 0.21686747, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.09090909, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.09090909, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.01282051, 0.01282051, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     